# following : https://raw.githubusercontent.com/wodby/docker4wordpress/master/docker-compose.yml

version: "3" # makes yml compatible w/ swarm mode
services:
  mariadb:
    image: wodby/mariadb:10.1-2.3.3
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
#    volumes:
#      - ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
#      - /path/to/mariadb/data/on/host:/var/lib/mysql # I want to manage volumes manually.
    deploy:
      replicas: 1
    networks:
      - kusamochi-traefik_public
      
  php:
    image: wodby/wordpress:4-7.1-2.2.0
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      # PHP_XDEBUG: 1
      # PHP_XDEBUG_DEFAULT_ENABLE: 1
      # PHP_XDEBUG_REMOTE_CONNECT_BACK: 0         # This is needed to respect remote.host setting bellow
      # PHP_XDEBUG_REMOTE_HOST: "10.254.254.254"  # You will also need to 'sudo ifconfig lo0 alias 10.254.254.254'
    volumes:
      - codebase:/var/www/html
    deploy:
      replicas: 1
    networks:
      - kusamochi-traefik_public
      
  nginx:
    image: wodby/wordpress-nginx:4-1.13-2.2.0
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html
    volumes:
      - codebase:/var/www/html
    depends_on:
      - php
    deploy:
      replicas: 1
      labels:
        - 'traefik.enable=true'
        - 'traefik.backend=nginx'
        - 'traefik.port=80'
        - 'traefik.frontend.rule=Host:wp.kusamochi.me'
        - 'traefik.docker.network=kusamochi-traefik_public'
    networks:
      - kusamochi-traefik_public

#  apache:
#    image: wodby/wordpress-apache:2.4-1.0.0
#    depends_on:
#      - php
#    environment:
#      APACHE_LOG_LEVEL: debug
#      APACHE_BACKEND_HOST: php
#      APACHE_SERVER_ROOT: /var/www/html
#    volumes:
#      - codebase:/var/www/html
## Options for macOS users (http://docs.docker4wordpress.org/en/latest/macos)
##      - codebase:/var/www/html:cached # User-guided caching
##      - docker-sync:/var/www/html # Docker-sync
#    labels:
#      - 'traefik.backend=apache'
#      - 'traefik.port=80'
#      - 'traefik.frontend.rule=Host:wp.docker.localhost'

#  varnish:
#    image: wodby/wordpress-varnish:4.1-2.2.0
#    depends_on:
#      - nginx
#    environment:
#      VARNISH_SECRET: secret
#      VARNISH_BACKEND_HOST: nginx
#      VARNISH_BACKEND_PORT: 80
#    labels:
#      - 'traefik.backend=varnish'
#      - 'traefik.port=6081'
#      - 'traefik.frontend.rule=Host:varnish.wp.docker.localhost'

#  redis:
#    image: wodby/redis:3.2-2.1.1

#  pma:
#    image: phpmyadmin/phpmyadmin
#    environment:
#      PMA_HOST: mariadb
#      PMA_USER: wordpress
#      PMA_PASSWORD: wordpress
#      PHP_UPLOAD_MAX_FILESIZE: 1G
#      PHP_MAX_INPUT_VARS: 1G
#    labels:
#      - 'traefik.backend=pma'
#      - 'traefik.port=80'
#      - 'traefik.frontend.rule=Host:pma.wp.docker.localhost'

#  athenapdf:
#    image: arachnysdocker/athenapdf-service
#    environment:
#      WEAVER_AUTH_KEY: weaver-auth-key
#      WEAVER_ATHENA_CMD: "athenapdf -S"
#      WEAVER_MAX_WORKERS: 10
#      WEAVER_MAX_CONVERSION_QUEUE: 50
#      WEAVER_WORKER_TIMEOUT: 90
#      WEAVER_CONVERSION_FALLBACK: false

  # mailhog:
  #   image: mailhog/mailhog
  #   labels:
  #     - 'traefik.backend=mailhog'
  #     - 'traefik.port=8025'
  #     - 'traefik.frontend.rule=Host:mailhog.wp.docker.localhost'

  portainer:
    image: portainer/portainer
    command: --no-auth
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1
      labels:
        - 'traefik.enable=true'
        - 'traefik.backend=portainer'
        - 'traefik.port=9000'
        - 'traefik.frontend.rule=Host:portainer.kusamochi.me'
        - 'traefik.docker.network=kusamochi-traefik_public'
    networks:
      - kusamochi-traefik_public

        
  # traefik:
  #   image: traefik
  #   command: --web --docker --docker.swarmmode --docker.watch --docker.domain=docker.localhost --logLevel=INFO
  #   ports:
  #     - '8000:80'
  #     - '8080:8080' # Dashboard
  #     - '443:443'
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - /dev/null:/traefik.toml
  #   labels:
  #     - "traefik.enable=false"
  #   deploy:
  #     replicas: 1
  #     placement:
  #       constraints: [node.role == manager]
  #     restart_policy:
  #       condition: on-failure

volumes:
  codebase:

networks:
  webnet:
  kusamochi-traefik_public:
    external: true