version: "3" # makes yml compatible w/ swarm mode
services:
  kusamochi-frontend:
    image: rochong/kusamochi-fe:latest
    deploy:
      replicas: 2
      labels:
      - "traefik.backend=kusamochi-frontend"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:test.kusamochi.me"
      - "traefik.docker.network=kusamochi-traefik_public"
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:3000"

networks:
  kusamochi-traefik_public:
    external: true
