version: "3" # makes yml compatible w/ swarm mode
services:
  website:
    image: rochong/kusamochi-fe:latest
    deploy:
      replicas: 2
      labels:
        - "traefik.backend=website"
        - "traefik.port=80"
        - "traefik.frontend.rule=Host:kusamochi.me"
        - "traefik.docker.network=kusamochi-traefik_public"
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    networks:
      - kusamochi-traefik_public

networks:
  kusamochi-traefik_public:
    external: true
